CREATE TABLE CINEMAS
(
    cinema_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
);

CREATE TABLE MOVIES
(
    movie_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    running_time NUMBER NOT NULL,
    synopsis VARCHAR(500) NOT NULL,
    poster_image VARCHAR(200) NOT NULL,
    release_year NUMBER(4) NOT NULL,
);

CREATE TABLE LANGUAGES
(
    language_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code VARCHAR(2) NOT NULL,
);

